### ISSUE TITLE
Weak ciphers supported: SSL_RSA_WITH_RC4_128_SHA

### ISSUE THREAD

**Issue by approached** [postalhq/postal#1004]
Postal use a weak ciphers. I have run the test via https://ssl-tools.net/mailservers/

My config:
```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/ssl/smtp.cert
  tls_private_key_path: /opt/postal/config/ssl/smtp.key
```
