### ISSUE TITLE
Cryptography Error in PSRP 

### ISSUE THREAD

**Issue by raf-rodrigues** [postalhq/postal#1101]
I have a problem with emails sent by Postal an error appears unencrypted.

I wanted to know how to proceed.

No gmail information that is sent via email via prsp.domain.com

But I will configure letsencrypt in the file

 /opt/postal/config/postal.yml

`smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/mail.domain.com/fullchai$
  tls_private_key_path: /etc/letsencrypt/live/mail.domain.com/privkey.$
  tls_ciphers: TLSv1_1
  ssl_version: TLSv1_1
`
But this message appears

https://ibb.co/MGC99JS

How to do psrp encryption?

**Comment by willpower232** [comment]
Have you restarted Postal since setting the config?

**Comment by raf-rodrigues** [comment]
Yes, I also reset the server and reactivated the Postal. He still says that domain.com did not encrypt this message.

**Comment by inspiretk** [comment]
You gave postal permission to the lets encrypt?

chown -R postal:postal /etc/letsencrypt

**Comment by raf-rodrigues** [comment]
Hello, yes I gave permission for the certificate.

But the problem still remains

**Comment by raf-rodrigues** [comment]
Would the Letsencrypt certificate I need be a wildcard?

**Comment by raf-rodrigues** [comment]
I’m sending it directly from the Postal panel,

**Comment by inspiretk** [comment]
/etc/letsencrypt/live/mail.domain.com/fullchai$ tls_private_key_path: /etc/letsencrypt/live/mail.domain.com/privkey.$ tls_ciphers: TLSv1_1 ssl_version: TLSv1_1

mail.domain.com - you need to change this to your domain name. Also, I dont have the other stuff you got "fullchai$ tls_private_key_path: " and "privkey.$ tls_ciphers: TLSv1_1 ssl_version: TLSv1_1"

I have
```
    tls_certificate_path: /etc/letsencrypt/live/mail.yourDomainName.com/fullchain.pem
    tls_private_key_path: /etc/letsencrypt/live/mail.yourDomainName.com/privkey.pem
```

I have this below for mine,
```
smtp_server:
    port: 25
    tls_enabled: true
    tls_certificate_path: /etc/letsencrypt/live/mail.yourDomainName.com/fullchain.pem
    tls_private_key_path: /etc/letsencrypt/live/mail.yourDomainName.com/privkey.pem
    proxy_protocol: false
    log_connect: true
    strip_received_headers: false
```

Make sure you restart postal when you update your config file: Command is:
```
postal stop
nano /opt/postal/config/postal.yml # change your config file and save it
postal initialize
postal start
```
