### ISSUE TITLE
SSL for SMTP

### ISSUE THREAD

**Issue by ivan006** [postalhq/postal#1112]
Please see my comment right at the end of this thread
https://github.com/postalhq/postal/issues/511
I tried to enable SSL for the SMTP signal but to no avail

**Comment by willpower232** [comment]
Please don't comment on closed issues.

When you say "to no avail" what error messages are you seeing?

**Comment by ivan006** [comment]
Ok i moved the comment here

I added the smtp_server settings to my postal.yml and restarted postal but when i test my smtp connection with SSL set the test fails. Here is the contents of my postal.yml file:

```
web:
  # The host that the management interface will be available on
  host: postal.outreach-hangar49.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.outreach-hangar49.com
  smtp_server_hostname: postal.outreach-hangar49.com
  spf_include: spf.postal.outreach-hangar49.com
  return_path: rp.postal.outreach-hangar49.com
  route_domain: routes.postal.outreach-hangar49.com
  track_domain: track.postal.outreach-hangar49.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 2939178bf71c9ec055bfde9ef6448cbf0e373b03e2ba11d18cc0e3c77cdfd1a11f3e307b1ad4817bfacb7459ea98c911218c7bcc8ccbb74777a1801aa8ca23423356dcb986eb515499660e6dc6e7ed44b5971083b108dec8f84aded6fb5e6f4613336d69590ca07d198905cdd22143f006062941fe51f14930eb98756ec25aaf

smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.outreach-hangar49.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.outreach-hangar49.com/privkey.pem

```
