### ISSUE TITLE
SSL tracking domain  - unknown SSL protocol error

### ISSUE THREAD

**Issue by danielboven** [postalhq/postal#1183]
I have been working on setting up the tracking domain for a while now, but I can't get one thing to work: using SSL for the tracking domain returns an error.

### Error occurring
For the command `curl https://click.postal.mydomain.com` the error is:
`curl: (35) Unknown SSL protocol error in connection to click.postal.mydomain.com:443`
In Chrome I get: `ERR_CONNECTION_RESET`

The server does respond without SSL. Running `curl http://click.postal.mydomain.com` returns `Hello`.

### VPS & domain provider
I have set up a secondary IP (ipv4 & ipv6) to be used for the tracking domain:
```
Primary
37.97.190.175         MAIN APP
2a01:7c8:aac2:344::1  MAIN APP

Secondary
37.97.193.2           TRACKING
2a01:7c8:aac2:344::2  TRACKING
```
The VPS network settings are configured as follows:

![vps](https://user-images.githubusercontent.com/55955019/90978398-f8f0e200-e54d-11ea-98a9-18c93c7dabdb.png)

I have added all 4 IP addresses to the Netplan YAML configuration (according to the instructions from my VPS provider). On the server the command `ip a` returns:
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:3f:52:ed brd ff:ff:ff:ff:ff:ff
    inet 37.97.190.175/24 brd 37.97.190.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet 37.97.193.2/24 brd 37.97.193.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 2a01:7c8:aac2:344:5054:ff:fe3f:52ed/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591982sec preferred_lft 604782sec
    inet6 2a01:7c8:aac2:344::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 2a01:7c8:aac2:344::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe3f:52ed/64 scope link 
       valid_lft forever preferred_lft forever
```

My DNS settings for the tracking domain are:

![DNS](https://user-images.githubusercontent.com/55955019/90978293-107b9b00-e54d-11ea-908a-668543e92273.png)

For the VPS my firewall settings are as follows:

![firewall](https://user-images.githubusercontent.com/55955019/90978809-c5638700-e550-11ea-83b4-6168c7749810.png)

### Setup of tracking domain (fast server)
To configure the tracking domain, I have followed the instructions from the wiki. Setting up Let's Encrypt returned `Done`. I have also updated the `postal.yml` file accordingly, it now looks like this:

```
web:
  # The host that the management interface will be available on
  host: postal.lawdashboard.nl
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 37.97.193.2

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: *******
  password: *******
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: *******
  password: *******
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: *******
  password: *******
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.lawdashboard.nl
  smtp_server_hostname: postal.lawdashboard.nl
  spf_include: spf.postal.lawdashboard.nl
  return_path: rp.postal.lawdashboard.nl
  dkim_identifier: postal
  route_domain: routes.postal.lawdashboard.nl
  track_domain: click.postal.lawdashboard.nl
```

Lastly, I have also updated the nginx configuration at `/etc/nginx/sites-enabled/default` and replaced the listen lines:
```
server {
    listen 37.97.190.175:443 ssl;
    root /opt/postal/app/public;
    server_name postal.lawdashboard.nl;
    ssl_certificate /etc/letsencrypt/live/postal.lawdashboard.nl/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/postal.lawdashboard.nl/privkey.pem; # managed by Certbot

    # Generate using: openssl dhparam 4096 -out /etc/ssl/dhparam.pem
    # ssl_dhparam /etc/ssl/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ************;

    location / {
       client_max_body_size 50M;
       try_files $uri $uri/index.html $uri.html @puma;
    }

    location /assets {
       add_header Cache-Control max-age=3600;
    }

    location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
    }

}
```

I have read through previous issues on using SSL with the tracking domain, but I have not found a solution for my problem. What could be the cause of this problem, or what more can I investigate?
