### ISSUE TITLE
550-Verification failed Permanent SMTP delivery error when sending to mail.remoteserver.com (xx.xx.xx.xx) 

### ISSUE THREAD

**Issue by mjml1982** [postalhq/postal#1199]
Hello,

Postal is marking emails as a hard bounce when I try to send email to a certain domain, I'm not using MX records for the sender domain as I'm using other mail services MX records to receive emails.

Permanent SMTP delivery error when sending to mail.remoteserver.com (xx.xx.xx.xx) 
550 5.1.0 MailProtect : Domain of sender address khcrqq@psrp.mydmain.com does not exist

Any help would be highly appreciated.

Thanks.

**Comment by willpower232** [comment]
If you have a look at the domains page, have you created the return path DNS records for it?

**Comment by mjml1982** [comment]
Yes, I have created the return path DNS record its verified and it looks like this.

CNAME
Host : psrp
Value:  rp.mail.mydomain.com

**Comment by mjml1982** [comment]
It's happening for some domains and it's delivering perfectly fine to other domains, yes I'm still getting this error now and its been many days after configuration once we start sending an email, I don't think its propagation delay.

**Comment by willpower232** [comment]
If the error message is `Domain of sender address ... does not exist` then it is likely to be a DNS problem. If it is still `psrp` related then that means the return path domain is not available to whatever is sending the bounce.

**Comment by mjml1982** [comment]
These are my DNS entries in postal.yml, what my DNS records should look like to fix this problem.

```
mx_records:
    - mail.mydomain.com
  smtp_server_hostname: mail.mydomain.com
  spf_include: spf.mail.mydomain.com
  return_path: rp.mail.mail.mydomain.com
  route_domain: routes.mail.mydomain.com
  track_domain: track.mail.mail.mydomain.com
```
