### ISSUE TITLE
Postal mail size issue

### ISSUE THREAD

**Issue by shakeeb91** [postalhq/postal#1204]
Hi,

I have tried sending email using ( postal SMTP ) and I am facing some trouble if i increase the max_message_size. So my postal.yml file contains below parameters for example:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/host_ssl/domain.pem
  tls_private_key_path: /etc/host_ssl/private/domain_key.pem
  tls_ciphers:
 max_message_size: 25 # size in Megabytes
```

Any Email less than or equal to 10MB passes successfully.

```
<-  250 OK
 -> QUIT
<-  221 Closing Connection
=== Connection closed with remote host
```

Any Email approx of equal to 20MB generates error that limit set to 

```
<** 552 Message too large (maximum size 25MB)
 -> QUIT
<-  221 Closing Connection
=== Connection closed with remote host.
```

So if I increase it to for example  max_message_size: 35 # size in Megabytes It starts generating an error for 11MB onwards file.

*** Remote host closed connection unexpectedly.

So my question is there any other limit define some where which terminates the connection ?

**Comment by willpower232** [comment]
If the above config is straight from your config file, it would be worth checking the indentation of the `max_message_size`

![image](https://user-images.githubusercontent.com/1619102/93064995-16f2c380-f670-11ea-88ca-6856ca04d679.png)

It would be worth checking your log files, particularly the `smtp_server.log` file which may contain the actual error message.

**Comment by shakeeb91** [comment]
Hi,

Sorry typo above indentation is fine. It looks like below

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/host_ssl/postal.prescreen.io_crt.pem
  tls_private_key_path: /etc/host_ssl/private/postal.prescreen.io_key.pem
  tls_ciphers:
  max_message_size: 35 ## size in Megabytes
```

**Comment by shakeeb91** [comment]
Hi,

Sorry to bother you finally I found the issue is in the MySQL database connection it is timeout because max_allowed_packet sets to 16MB once I set it to like 64MB is starts working well and sending email smoothly.

Regards,
Shakeeb

**Comment by willpower232** [comment]
thanks for letting us know, I'm sure that will come in handy

**Comment by brightcolor** [comment]
> shakeeb91

Can you pls tell me how do you set the MySQL max_allowed_packet?

**Comment by rakurtz** [comment]
I am also having this issue. This is my postal file:


## my config
```
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: xxxx
  password: xxxx
  from_name: Postal
  from_address: mydomain.com
  max_message_size: 50
```


## the error
this ist from the logs:
```
2024-07-26T10:47:50.671732+02:00 postal postal-smtp[869]: 2024-07-26 08:47:50 +0000 DEBUG  #033[34m=> 552 Message too large (maximum size 14MB)#033[0m trace_id=ENNYP98B component=smtp-server
```

these are the actual protocol messages (the client's view)
```
reply: b'552 Message too large (maximum size 14MB)\r\n'
reply: retcode (552); Msg: b'Message too large (maximum size 14MB)'
data: (552, b'Message too large (maximum size 14MB)')
send: 'rset\r\n'
reply: b'250 OK\r\n'
reply: retcode (250); Msg: b'OK'
send: 'QUIT\r\n'
reply: b'221 Closing Connection\r\n'
reply: retcode (221); Msg: b'Closing Connection'
An error occurred: (552, b'Message too large (maximum size 14MB)')
```

## what i tried 
1. restartet postal after adjusting the config file
2. in maria db: `SET GLOBAL max_allowed_packet=104857600;` (100 MB)

checked: 
```
MariaDB [(none)]> SHOW VARIABLES LIKE 'max_allowed_packet';
+--------------------+-----------+
| Variable_name      | Value     |
+--------------------+-----------+
| max_allowed_packet | 104857600 |
+--------------------+-----------+
1 row in set (0.002 sec)
```


any ideas on where to look or what measures to take?
