### ISSUE TITLE
Postal DNS config is unverified

### ISSUE THREAD

**Issue by vnkrish90** [postalhq/postal#1261]
I have installed postal mail server in ubuntu 18.04 digital ocean VPS machine. Added SPF record with "v=spf1 a mx include:spf.smtp.mydomain.in ~all". In my `postal.yml` file added spf record `spf.postal.example.com But my domain's spf and dkim records are not verfied.

https://ibb.co/rGFkbsM

my postal config looks like this,
```
web:
  # The host that the management interface will be available on
  host: smtp.wandresearch.in
  # The protocol that requests to the management interface should happen on
  protocol: https
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.example.com
  smtp_server_hostname: postal.example.com
  spf_include: spf.postal.example.com
  return_path: rp.postal.example.com
  route_domain: routes.postal.example.com
  track_domain: track.postal.example.com
```
