### ISSUE TITLE
Emails blocked by different providers. Can't figure out what cause the problem.

### ISSUE THREAD

**Issue by maks200179** [postalhq/postal#1295]
### Hi there .
Please help me, that broke my mind :).
Thank for future advice .

I have almost same issue like in this link 
https://github.com/postalhq/postal/issues/146

I have configured my DKIM, SPF and DMARC records correctly.
There are A records pointing to my server so using telnet everything look fine .

I have tried deferent email providers, almost return a error .
mail.ru return '550 non-local sender verification failed'

The Gmail put my emails to spam automatically. 

 

Gmail headers, of email sanded , from postal :

```
Delivered-To: maxfr12227979@gmail.com
Received: by 2002:ab0:1548:0:0:0:0:0 with SMTP id p8csp625817uae;
        Wed, 3 Feb 2021 15:13:59 -0800 (PST)
X-Google-Smtp-Source: ABdhPJw5xROdFM+MG/MuUs035NkBNRGvoIvQSU+AmGVjEf1MyIlmzfsEfI0wEQABpAEJBO12j+Uz
X-Received: by 2002:a17:906:e106:: with SMTP id gj6mr5304785ejb.337.1612394039050;
        Wed, 03 Feb 2021 15:13:59 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1612394039; cv=none;
        d=google.com; s=arc-20160816;
        b=ielo/RLHla/QlMbDEqOgCPygaXyPsyl31lJvtYHdrbGuXBqeecPgFX2Cg+l8/2XPRj
         zKKQu2BJkgI06FGq+nDNg+5v7bWE3pTEsDI/L25uTKFsr9Jrcl++E6+GW4UrJQLvAxSy
         +0Orki9P/xUls2HqaGOU36QsN96UQYkz6AWrfZzN+5E8t7Ntgg0UuvHEc5MSpIMO1rpb
         Sj/x/Yh3wY4WWl/TPd2XfI1HXv6IvT3OBpLCvtG0P6Zmi+qdHkDeDhb6vk4rNUMvcw76
         nluNSO9VSjv83rbFnM/gq3swBsG7c9KW+U6poDdK+DJzYUpRg9CGs4Lced4MUpryA//S
         FyNA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:mime-version:subject:message-id:to:from
         :date:dkim-signature:resent-sender;
        bh=RwML7bZTV0QEdoeJq45vt7A1976/m7ol7MMBjBCLcIM=;
        b=LheGMxSOSarkVySKY1DwpRtfzeamis3j1+Xd5Xw3mmjqoXlXfzIngxrhAxS9MWNBxR
         IfHIt9TL/kFqSjv+lJ7JQkM1i7F8jvpTllFMxVpjhIWdBPUu1r54V3NQgQL47TyJDMVR
         NFrjuo6AFpJrEW2RDHZyIn5IPmEyBdq30gqfzBqoiuWH8ofTit0r4a0BYCzwWMy81J/J
         p7JcozKgHSKy4xfI9nNfUtr8uI+WRP3CtHdC6tqSiOzQ0syd4L93+vOBp6Q4t1+k76YG
         OzgO1itpTsjeFr7ZsmU3L3eiCKhWiTa+k+ZsQvtlsic5eZ025l/Bz+e0dq1J06168WGR
         5YNA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=neutral (body hash did not verify) header.i=@xxxmaxfr.com header.s=postal-Adzx8X header.b=hycIOfA1;
       spf=neutral (google.com: 84.228.160.102 is neither permitted nor denied by best guess record for domain of cughzi@psrp.xxxmaxfr.com) smtp.mailfrom=cughzi@psrp.xxxmaxfr.com
Return-Path: <cughzi@psrp.xxxmaxfr.com>
Received: from mail.xxxmaxfr.com (IGLD-84-228-160-102.inter.net.il. [84.228.160.102])
        by mx.google.com with ESMTPS id z17si2320314edl.91.2021.02.03.15.13.58
        for <maxfr12227979@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Wed, 03 Feb 2021 15:13:59 -0800 (PST)
Received-SPF: neutral (google.com: 84.228.160.102 is neither permitted nor denied by best guess record for domain of cughzi@psrp.xxxmaxfr.com) client-ip=84.228.160.102;
Authentication-Results: mx.google.com;
       dkim=neutral (body hash did not verify) header.i=@xxxmaxfr.com header.s=postal-Adzx8X header.b=hycIOfA1;
       spf=neutral (google.com: 84.228.160.102 is neither permitted nor denied by best guess record for domain of cughzi@psrp.xxxmaxfr.com) smtp.mailfrom=cughzi@psrp.xxxmaxfr.com
Resent-Sender: cughzi@psrp.xxxmaxfr.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=xxxmaxfr.com; s=postal-Adzx8X; t=1612394037; bh=+ESn9ALTRi6ARpK6byMSwGuOWq1ov3AMtZD/HY4DxAE=; h=date:from:to:message-id:subject:mime-version:content-type:content-transfer-encoding; b=hycIOfA1O90MRzwriR90c+BM9V+A1GCKLCI7/JpAoB9M2V1yXGZzqsKp3zcQeqhULKutPJusZ4Ge0sdtPKSnFlJHRSZBmCoxTl9chWkASvGn1rNzGiNFwfauKJxScZx+Rg+he67U8tBR6U6DsPt8CpiJnZkfaItqjI79PzDHTEs=
X-Postal-MsgID: jh7r7E4B379S
Received: from web-ui (proxyserver.home-test-email-validator_infrastructure [172.22.0.3]) by Postal with HTTP; Wed, 03 Feb 2021 23:13:57 +0000
Date: Wed, 03 Feb 2021 23:13:57 +0000
From: maksim123@xxxmaxfr.com
To: maxfr12227979@gmail.com
Message-ID: <fb777479-79ff-4f29-ba57-604f2e7138d7@rp.mail.xxxmaxfr.com>
Subject: Test Message at February 03, 2021 23:13
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

just test mu email 
```

### I think that i know what cause the problem but i don't know how to resolve it .
This line below come from my revers proxy docker .

### Received: from web-ui (proxyserver.home-test-email-validator_infrastructure [172.22.0.3]) by Postal with HTTP; Wed, 03 Feb 2021

But i use smtp on localhost port 25 of postal inside docker, and map the port to host machine like this.
I really do not understand how is it work.
I think that my postal docker should send emails out via port 25 smtp , but why the "Received: from" header  has proxyserver hostname, from inside other container, which serve on port 80 and 445 postal GUI  ? 

```
      postal:
        #image: catdeployed/postal:alpine
        build:
            context: postal/
            dockerfile: Dockerfile
        container_name: postal
        privileged: true  
        command: run
        ports:
          - 0.0.0.0:25:25
        depends_on:
          - "mysql"
          - "rabbitmq"
        volumes:
          - ./postal/data/persistent_assets:/storage
          
          - ./postal/data/config/lets_encrypt.pem:/opt/postal/config/lets_encrypt.pem
          - ./postal/data/config/signing.key:/opt/postal/config/signing.key
          #- ./postal/data/postal_assets:/opt/postal/public/assets
          - ./postal/src/templates/:/templates
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=postal
          - RABBITMQ_DEFAULT_USER=postal
          - RABBITMQ_DEFAULT_PASS=changeme
          - RABBITMQ_DEFAULT_VHOST=postal
          - POSTAL_FNAME=Sia
          - POSTAL_LNAME=Cat
          - POSTAL_PASSWORD=StrongPassword
          - POSTAL_EMAIL=maximov@xxxmaxfr.com
        healthcheck:
          test: curl -sS --resolve http://postal.home.test:5000:127.0.0.1 http://postal.home.test:5000 || exit 1
          interval: 5s
          timeout: 10s
          retries: 3
        networks:
            infrastructure:
                aliases:
                    - postal.home.test







    proxyserver:
        container_name: proxyserver
        build:
            context: ./proxyserver/
            dockerfile: Dockerfile
        #volumes:
            #- ./proxyserver/config/certs:/etc/ssl/certs
            #- ./proxyserver/config/private:/etc/ssl/private 
        ports:
            - "80:80"
            - "443:443"
            - "42:22"
        networks:
            - infrastructure
        tty: true
        
        depends_on:
            - postal
            
networks:
    infrastructure:
        driver: bridge







dns:
  mx_records:
    - mail.xxxmaxfr.com
  smtp_server_hostname: mail.xxxmaxfr.com
  spf_include: spf.mail.xxxmaxfr.com
  return_path: rp.mail.xxxmaxfr.com
  route_domain: routes.mail.xxxmaxfr.com
  track_domain: track.mail.xxxmaxfr.com
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp


```

### mxtoolbox.com report 'smtp lockup '

  SMTP Banner Check Reverse DNS does not match SMTP Banner | Warning
  SMTP TLS | Warning - Does not support TLS.
  SMTP Transaction Time | 8.564 seconds - Not good! on Transaction Time
  SMTP Reverse DNS Mismatch OK - 84.228.160.XXX resolves to IGLD-84-228-160-XXX.inter.net.il  
  SMTP Valid Hostname OK - Reverse DNS is a valid Hostname  
  SMTP Connection Time 0.617 seconds - Good on Connection time  
  SMTP Open Relay OK - Not an open relay.  

Connecting to 84.228.160.XXX

220 mail.xxxmaxfr.com ESMTP Postal/BNVK2P [464 ms]
EHLO keeper-us-east-1c.mxtoolbox.com
250-My capabilities are
250 AUTH CRAM-MD5 PLAIN LOGIN [726 ms]
MAIL FROM:supertool@mxtoolboxsmtpdiag.com
250 OK [260 ms]
RCPT TO:test@mxtoolboxsmtpdiag.com
530 Authentication required [6813 ms]

LookupServer 9390ms

### The other questions is :
 i have mounted this files  because postal fail after reboot on error:
    /opt/postal/lib/postal/config.rb:198:in `check_config!': No Let's Encrypt private key found at /opt/postal/config/lets_encrypt.pem (Postal::ConfigError)
          volumes:
              - ./postal/data/config/lets_encrypt.pem:/opt/postal/config/lets_encrypt.pem
              - ./postal/data/config/signing.key:/opt/postal/config/signing.key
