### ISSUE TITLE
How to properly configure return path to receive bounces in the correct mailbox

### ISSUE THREAD

**Issue by afanjul** [postalhq/postal#1298]
Hi there, I've been working with Postal since years ago, but now I'm awaring of a thing that I didn't realize before, and that is that we are not receiving the bounces emails to our mailboxes (for example autoresponders). So what is the correct way to configure the postal server so that the next example works fine (asuming **domain.com** is a domain configured in Postal that is installed in **mailserver.com** acting as outgoing/smtp server) ?

- user1@domain.com send mail to external@gmail.com that has an autoresponder, so user1@domain.com receive a message with the auto-response.
- user2@domain.com send mail to external@gmail.com that has an autoresponder, so user2@domain.com receive a message with the auto-response. 

_I use a two users/address examples to remark the need of each one receive his own "bounced" autoresponder, and not to have a "catch-all bounces" address or something like that._ 

******************************
In our case, based on our tests, the auto-responses are been sending to rrktbj@psrp.domain.com which could be good **but are getting trapped in Postal** (and never reach the original sender mailbox) as you can see in the screenshot. Moreover it cannot link it to the original mail sent  :
![image](https://user-images.githubusercontent.com/2046424/107373356-bd8ba500-6ae6-11eb-93eb-fa5527cac080.png)

******************************
**My postal.yml:**
```
mx_records:
 -mx.mail.mailserver.com
smtp_server_hostname: mail.mailserver.com
spf_include: spf.mail.mailserver.com
return_path: rp.mail.mailserver.com
route_domain: routes.mail.mailserver.com
track_domain: track.mail.mailserver.com
```
******************************
**My DNS zone for the mailserver:**
```
;; A Records
mail.mailserver.			1	IN	A	xxx.xxx.203.204
mailserver.				1	IN	A	xxx.xxx.203.204
track.mail.mailserver.		1	IN	A	212.129.14.126

;; AAAA Records
mail.mailserver.			1	IN	AAAA	fe80::250:56ff:fe01:28dc
track.mail.mailserver.		1	IN	AAAA	fe80::250:56ff:fe01:28dc

;; CNAME Records
mx.mail.mailserver.			1	IN	CNAME	mail.mailserver.
rp.mail.mailserver.			1	IN	CNAME	mail.mailserver.

;; MX Records
routes.mail.mailserver.		1	IN	MX	10 mx.mail.mailserver.
rp.mail.mailserver.			1	IN	MX	10 mx.mail.mailserver.

;; TXT Records
mailserver.				1	IN	TXT	"v=spf1 include:mx.ovh.com ~all"
rp.mail.mailserver.			1	IN	TXT	"v=spf1 a mx include:spf.mail.mailserver ~all"
spf.mail.mailserver.			1	IN	TXT	"v=spf1 ip4:xxx.xxx.203.204 ip4:xxx.xxx.147.102 ip4:xxx.xxx.14.126 ip4:xxx.xxx.124.163 ~all"
postal._domainkey.rp.mail.mailserver.	1	IN	TXT	"v=DKIM1;......."
```
---------------------
**My DNS zone for the domain configured in Postal:**

![image](https://user-images.githubusercontent.com/2046424/107373161-7f8e8100-6ae6-11eb-9ee3-18c0ec3912f6.png)

All that been said, we are using our own separated Incoming Mail server for the "domain.com".
Thanks
PS: All info and data has been "changed/obfuscated" even in screenshots for security.

**Comment by willpower232** [comment]
Postal is designed to handle transactional email from software and as such you currently need to configure a return path route so that Postal knows what to do with the returned emails, i.e. direct them back to the application that sent them in a way it can understand.

There is more detail in the wiki https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces

It sounds like you're using this for direct person-to-person email so I'm not sure this will serve you that well.

**Comment by gsommavilla** [comment]
I am in a situation similar to @afanjul 's:

- let's call my domain MYDOMAIN.COM
- I intend to use postal only to send emails (not to receive)
- I already have another service that takes care of receiving emails
  on MYDOMAIN.COM (for this domain there are already DNS records of
  type MX, SPF, etc.)
- my postal.yml configuration is

    ```
    dns:
      mx_records:
        - MYDOMAIN.COM                                                                           
      smtp_server_hostname: MYDOMAIN.COM                                                         
      spf_include: spf.MYDOMAIN.COM                                                         
      return_path: rp.MYDOMAIN.COM                                                         
      route_domain: routes.MYDOMAIN.COM                                                          
      custom_return_path_prefix: psrp                                                         
    ```

I read the documentation at
https://github.com/postalhq/postal/wiki/Auto-Responders-&-Bounces
but several things are unclear to me:

- I don't understand the purpose of having a "return path route",
  because I read in the documentation that "Once added [the return
  path route], messages sent to your return path that aren't detected
  as bounces will be sent to HTTP endpoint you choose". But if the
  return path is something like `k28jue@rp.MYDOMAIN.COM`, it seems to
  me that it is fairly impossible that someone/something wants to send
  actual emails (that are not bounce) to that email account. Am I
  missing something here?

- if I still want use my own incoming email server (and not use postal
  for receiving emails):

  1. are webhooks the only way I can be notified of events such as
     `MessageDeliveryFailed` or `MessageBounced`? I ask this because
     if I send an email to a non-existant account (f.e. on gmail.com),
     I usually receive an "Undelivered Mail Returned to Sender"

  2. how can I configure DNS records for return path
     (i.e. `rp.MYDOMAIN.COM`)?
