### ISSUE TITLE
How to test Fast Server, Tracking and Tracking SSL?

### ISSUE THREAD

**Issue by Igcorreia** [postalhq/postal#1350]
Hi, I am in the process of implementing tracking on postal, I followed the following steps: 

1.  Configure config.yml as-is:
```
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.us-1.mail.mydomain.com
  smtp_server_hostname: us-1.mail.mydomain.com
  spf_include: spf.us-1.mail.mydomain.com
  return_path: rp.us-1.mail.mydomain.com
  route_domain: routes.us-1.mail.mydomain.com
  track_domain: track.us-1.mail.mydomain.com
  helo_hostname: us-1.mail.mydomain.com
  dkim_identifier: mydomain
  domain_verify_prefix: mydomain-verification
  custom_return_path_prefix: adrp
```
note: as you can see I customized all of the options
2.  The tacking domain is going to be: track.us-1.mail
3.  I have configured it as a A record to the web_server IP

I need help figuring a few things, what is the correct DNS configuration for tracking? Should I point it to a different IP address? How should I configure SSL?

Or I did right and it should just work?
How do I test it?
