### ISSUE TITLE
Replacements in postal.yml

### ISSUE THREAD

**Issue by dxxbdoobdxxb** [postalhq/postal#1384]
If my hostname is = notify.mydomain.com

How do I make the replacements in postal.yml?

For every line with postal.example.com

Do I replace just example.com like postal.mydomain.com OR should I replace postal.example.com with notify.mydomain.com?

Please advice thanks 🙏

**Comment by willpower232** [comment]
> replace postal.example.com with notify.mydomain.com

so you would have something like
```
dns:
    mx_records:
      - mx.notify.mydomain.com
    smtp_server_hostname: notify.mydomain.com
    spf_include: spf.notify.mydomain.com
    return_path: rp.notify.mydomain.com
    route_domain: routes.notify.mydomain.com
    track_domain: track.notify.mydomain.com
```
