### ISSUE TITLE
Docker: Do we need to use host networking?

### ISSUE THREAD

**Issue by jaydrogers** [postalhq/postal#1420]
# Background
The Postal image has the networking set to `host`: 
https://github.com/postalhq/install/blob/67ccc6972dafd50bd92c5367da414f537838251a/docker-compose.yml#L6

# Question
```
Would it be possible to just pass the ports through to a Docker network?
```
**Example:**
```yaml
smtp:
    image: postalhq/postal:latest
    command: bundle exec rake postal:smtp_server
    networks:
    	- postal
    ports:
     - "25:2525"
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
 ```

### Advantages
* We would be able to easily run the containers on a Docker network
* This would make it easier for running with other services (like Caddy or Traefik)
* Moving the services to a docker network will allow us to remove these complexities at the bottom of the README. We can provide all of this for the user out of the box

**What we could remove from the install README:**
![image](https://user-images.githubusercontent.com/3174134/127227506-fcab0ffd-57af-43ea-9e5e-02078d122c79.png)

### Disadvantages
* Some people may change ports but forget to change them in their docker file

# Next steps
@adamcooke: Let me know you think.
