### ISSUE TITLE
Docker: Include service dependencies in "docker-compose.yml" example

### ISSUE THREAD

**Issue by jaydrogers** [postalhq/postal#1421]
# Background
In the [Install README](https://github.com/postalhq/install#service-dependencies), there are service dependencies required.

![image](https://user-images.githubusercontent.com/3174134/127228062-05eac87b-efa8-4e45-aae8-952b95692c1a.png)

# Problem
* This makes the user experience for starting Postal confusing. It's like we're providing them a template to get started, but not giving them the full solution

# Proposed solution
* Since these dependencies are required, we should provide the most complete example possible (so people can simply run `docker-compose up` to get started
* Advanced users (with their external services) will be smart enough to modify and remove the services they will not need

# Next steps
@adamcooke: Let me know your thoughts.

**Comment by adamcooke** [comment]
I did originally do this but I don't actually want any responsibility for external services. We provide the Postal software and I don't want to worry about how people deploy, scale and manage their external services. 

While I do want to provide simple install docs, I don't think asking a user to install a couple of dependencies themselves is too much effort. In our docs we have provide a very quick way to get running with Docker (albeit not very secure). Users need to know what they're bringing up here and what passwords they are choosing.

Another issue is having the dependencies in the compose file means we have to orchestrate things so that the installation is brought up in the correct way.

1. Start the DB components
2. Wait for them to start
3. Run the `init_db` task
4. Start the rest of the components

**Comment by willpower232** [comment]
> 2. Wait for them to start

For future reference RabbitMQ makes this particularly painful, I had to add wait-for-it.sh to my messing around with Postal and Docker to guarantee that it had started before Postal.

**Comment by adamcooke** [comment]
FWIW the Postal container does include a wait-for entrypoint to allow for this.

**Comment by jaydrogers** [comment]
Nice! Would you mind sharing a little more on that?

I was going to put together a "turn key" solution using Docker Compose. I was planning on using the "depends_on" with the wait script if you have it https://docs.docker.com/compose/startup-order/

**Comment by pjv** [comment]
@jaydrogers I've created a simple `postal_reqs` docker-compose file that brings up containers for caddy, rabbitmq, and mariadb. i was thinking about adding the contents of the postal install docker-compose file to it with `depends-on` (and also restart statements) so i could do a single `docker-compose up -d` and reliably restart the whole postal stack. Is that what you had in mind? Have you gotten anywhere on building and testing it?

**Comment by pjv** [comment]
Here’s a WIP `docker-compose.yml` “with batteries included” that starts, puts up the UI, and seems to be logging reasonable things. I won’t be able to test the actual mail sending part until I’m confident enough in Postal v2 to swap my IP addresses from the old box running Postal v1.

note that running postal this way disconnects it from the `postal` command “binary” that gets installed with the normal install method. One would either need to substitute docker-compose commands (i.e. instead of `postal status`, you’d `docker-compose ps`), or would need to re-write the `postal` command to go along with this method of running the postal stack. 

````
version: "3.9"
services:
  caddy:
    image: caddy:alpine
    container_name: postal-caddy
    restart: unless-stopped
    network_mode: host # using ip pools
    volumes:
      - /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile
      - /opt/postal/caddy-data:/data

  mariadb:
    image: mariadb
    container_name: postal-mariadb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: <super sekret>
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - dbdata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.9
    container_name: postal-rabbitmq
    restart: unless-stopped
    ports:
      - "127.0.0.1:5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: postal
      RABBITMQ_DEFAULT_PASS: <super sekret>
      RABBITMQ_DEFAULT_VHOST: postal
    volumes:
      - mqdata:/var/lib/rabbitmq/mnesia/

  web:
    image: ghcr.io/postalserver/postal:2.0.0
    command: postal web-server
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

  smtp:
    image: ghcr.io/postalserver/postal:2.0.0
    command: postal smtp-server
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

  worker:
    image: ghcr.io/postalserver/postal:2.0.0
    scale: 8 # adjust for the resources available and needed
    command: postal worker
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

  cron:
    image: ghcr.io/postalserver/postal:2.0.0
    command: postal cron
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

  requeuer:
    image: ghcr.io/postalserver/postal:2.0.0
    command: postal requeuer
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:2.0.0
    command: postal
    network_mode: host
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
    depends_on:
      - mariadb
      - rabbitmq
    environment:
      WAIT_FOR_TARGETS: 127.0.0.1:3306 127.0.0.1:5672

volumes:
  dbdata:
  mqdata:
````
