### ISSUE TITLE
SSL and TLS on Mail Server

### ISSUE THREAD

**Issue by ashish244268** [postalhq/postal#511]
I have successfully setup everything but now I will like to go further 
1. How can I register user?
2. How can user add his own mail server on his own domain?
3. How can I enable SSL and TLS on Mail Server?

thanks

**Comment by willpower232** [comment]
1. if you want to make system administators, you will need to use `postal make-user` but if you only want to give them access to one organisation and make them verify each domain they add you need to use the users UI in the system

![image](https://user-images.githubusercontent.com/1619102/36740682-1c2c93de-1bdb-11e8-9a6c-00dcfacac2b2.png)

2. either user above should be able to create the mail server

3. You will need to use the certificate you may already have for accessing the UI and update these config options https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L68-L70

**Comment by ashish244268** [comment]
NO,
I think you are not getting my point here.
okay Let me ask this way:
How can I use postal for bulk mailing?
for example, I just create a user and then my user login and upload his list of 200k mail and send same campaign on all those 200k mails 
can we do this?

You will need to use the certificate you may already have for accessing the UI and update these config options https://github.com/atech/postal/blob/master/config/postal.defaults.yml#L68-L70
>>>>>>>>> I will test this....!

**Comment by phelset** [comment]
https://github.com/atech/postal/wiki/FAQs#can-you-add-mailing-list-feature

**Comment by ivan006** [comment]
I added the smtp_server settings to my postal.yml and restarted postal but when i test my smtp connection with SSL set the test fails. Here is the contents of my postal.yml file:

```
web:
  # The host that the management interface will be available on
  host: postal.outreach-hangar49.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: true

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.outreach-hangar49.com
  smtp_server_hostname: postal.outreach-hangar49.com
  spf_include: spf.postal.outreach-hangar49.com
  return_path: rp.postal.outreach-hangar49.com
  route_domain: routes.postal.outreach-hangar49.com
  track_domain: track.postal.outreach-hangar49.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: 2939178bf71c9ec055bfde9ef6448cbf0e373b03e2ba11d18cc0e3c77cdfd1a11f3e307b1ad4817bfacb7459ea98c911218c7bcc8ccbb74777a1801aa8ca23423356dcb986eb515499660e6dc6e7ed44b5971083b108dec8f84aded6fb5e6f4613336d69590ca07d198905cdd22143f006062941fe51f14930eb98756ec25aaf

smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.outreach-hangar49.com/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/postal.outreach-hangar49.com/privkey.pem

```
