### ISSUE TITLE
Try everything but unable to work tls encryption I have a SSl certificate also

### ISSUE THREAD

**Issue by shaheryar2014** [postalhq/postal#803]
Hi

I have a ssl Certificate completely integrated with postal by checking the certificate status

https://www.ssllabs.com/ssltest/analyze.html?d=mail.dailydeals360.com

It says the certificate is fine. Also implemented on web which is showing ssl sign fine in green url is 

https://mail.dailydeals360.com

But unable to activate starttls encryption. when i check starttls with this command

openssl s_client -connect mail.dailydeals360.com:25 -starttls smtp

CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 142 bytes and written 340 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1556547277
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
It gives me the above message

Also Attaching postal.yml file for understanding

[postal.txt](https://github.com/atech/postal/files/3127744/postal.txt)

and the last thing i am using mailwizz as a mail transfer agent (MTA). When i try to validate the server in port 25 starttls configuration it gives me this message

Connection could not be established with host mail.dailydeals360.com [Unable to find the socket transport "starttls" - did you forget to enable it when you configured PHP? #32751]
Log data:
++ Starting Swift_SmtpTransport
!! Connection could not be established with host mail.dailydeals360.com [Unable to find the socket transport "starttls" - did you forget to enable it when you configured PHP? #32751] (code: 0).

Please help me out in this connection 

Right now my server is fully working and can send email without TLS perfectly and email tracking also working and enabled. Test email working fine

Thank You

**Comment by tchwpkgorg** [comment]
In /opt/postal/config/postal.yml I have:
```

smtp_server:
  port: 25
  tls_enabled: true
  tls_certificate_path: /opt/postal/ssl/fullchain.pem
  tls_private_key_path: /opt/postal/ssl/privkey.pem
  tls_ciphers: kEECDH:+kEECDH+SHA:kEDH:+kEDH+SHA:+kEDH+CAMELLIA:kECDH:+kECDH+SHA:kRSA:+kRSA+SHA:+kRSA+CAMELLIA:!aNULL:!eNULL:!SSLv2:!RC4:!MD5:!DES:!EXP:!SEED:!IDEA:!3DES
  ssl_version: TLSv1_2
  proxy_protocol: false
  log_connect: true
  strip_received_headers: true
  max_message_size: 14 # size in Megabytes

```
