### ISSUE TITLE
Having an internal smtp host without TLS

### ISSUE THREAD

**Issue by vishnus** [postalhq/postal#876]
Hi,

Currently the smtp_server config has:

```
smtp_server:
  tls_enabled: true
  tls_certificate_path: /opt/postal/config/comodo.cert
  tls_private_key_path: /opt/postal/config/comodo.key
```

It works fine with a TLD with valid certificates and all, but if we have an internal server (With an internal DNS like smtp.companyname) which try to send email to postal through LAN via 25 without TLS, it fails saying invalid certificate for the domain. Is it possible to have a different SMTP server with TLS not enabled within the same system?
