### ISSUE TITLE
Question about configuring dns

### ISSUE THREAD

**Issue by hosnas** [postalhq/postal#963]
I followed the configuration of dns. Now I get email correctly. However I think its not optimal. What I see from gmail about sender informaion is somthing like this:

mailed-by: | rp.postal.zabanshenas.com
-- | --
signed-by: | rp.postal.zabanshenas.com

However If I use somthing like sendgrid, I get somthing like:

mailed-by: | send.zabanshenas.com
-- | --
signed-by: | zabanshenas.com

How can I achieve similar result with postal? I mean I prefer somthing like :

mailed-by: | postal.zabanshenas.com
-- | --
signed-by: | zabanshenas.com

**Comment by willpower232** [comment]
I can't replicate what you're seeing. Are you able to tell us which DNS records you have configured?

**Comment by hosnas** [comment]
@willpower232  This is all the dns I have configured in my cloudflare

![image](https://user-images.githubusercontent.com/26921196/72003746-43dc1480-325f-11ea-8ebc-132126348d70.png)

**Comment by hosnas** [comment]
btw I have configured the dns, however I still get this warning:

![image](https://user-images.githubusercontent.com/26921196/72048039-25166600-32d1-11ea-9753-3ad88fa223b6.png)

**Comment by willpower232** [comment]
And you're definitely adding zabanshenas.com to your Postal server, not a subdomain?

**Comment by hosnas** [comment]
I'm using a subdomain. Is there somthing wrong?

```yaml
web:
  # The host that the management interface will be available on
  host: postal.zabanshenas.com
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: p0stalpassw0rd
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: sdf
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: sdf
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.zabanshenas.com
  smtp_server_hostname: postal.zabanshenas.com
  spf_include: spf.postal.zabanshenas.com
  return_path: rp.postal.zabanshenas.com
  route_domain: routes.postal.zabanshenas.com
  track_domain: track.postal.zabanshenas.com

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: sdfsdfsdf
```
