### ISSUE TITLE
Tracking Domain CNAME not configured correctly

### ISSUE THREAD

**Issue by gazidizdaroglu** [postalhq/postal#979]
Hello.

I can't configure tracking domain CNAME.  Here is the my configuration on `postal.yml`

```
dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.mailserver.XXX.com
  smtp_server_hostname: mailserver.XXX.com
  spf_include: spf.mailserver.XXX.com
  return_path: rp.mailserver.XXX.com
  route_domain: routes.mailserver.XXX.com
  track_domain: track.mailserver.XXX.com
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp
```

How I should add the records for Open & Tracking? If you explain how I can enable Open & Tracking I would really appreciate it!
